site_name: tra-doc

nav:
 - Overview: index.md
 - Components/Projects:
   - itra:
     - itra-libs: components/itra/itra-libs/Overview.md
     - itra-behavior: components/itra/tra-behavior/Overview.md

   - tra:
     - tra-orch: components/tra-orch/Overview.md
     - tra-inf: components/tra-inf/Overview.md
     - tra-math: components/tra-math/Overview.md
     - tra-planning: components/tra-planning/Overview.md
     - tra-parser: components/tra-parser/Overview.md
     - proposal-sampler: components/proposal-sampler/Overview.md
     - tra-tools: components/tra-tools/Overview.md
   
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: "#"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
